# Generated by Django 5.1.6 on 2025-11-29 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy_App', '0009_userstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfersInDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hometown', models.CharField(default='Monroe NY:)', max_length=100)),
                ('tour', models.CharField(default='PGA', max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
