# Generated by Django 5.1.6 on 2025-11-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy_App', '0011_usertrackedgolfers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrackedgolfers',
            name='golfers',
        ),
        migrations.AddField(
            model_name='usertrackedgolfers',
            name='selection1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot1_users', to='Fantasy_App.golfersindatabase'),
        ),
        migrations.AddField(
            model_name='usertrackedgolfers',
            name='selection2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot2_users', to='Fantasy_App.golfersindatabase'),
        ),
        migrations.AddField(
            model_name='usertrackedgolfers',
            name='selection3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot3_users', to='Fantasy_App.golfersindatabase'),
        ),
        migrations.AddField(
            model_name='usertrackedgolfers',
            name='selection4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot4_users', to='Fantasy_App.golfersindatabase'),
        ),
        migrations.AddField(
            model_name='usertrackedgolfers',
            name='selection5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot5_users', to='Fantasy_App.golfersindatabase'),
        ),
    ]
