# Generated by Django 5.1.6 on 2025-12-04 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy_App', '0013_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolferScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('score', models.IntegerField()),
                ('relative_to_par', models.IntegerField(blank=True, null=True)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Fantasy_App.golfersindatabase')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Fantasy_App.tournament')),
            ],
        ),
    ]
