# Generated by Django 5.1.6 on 2025-12-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy_App', '0014_golferscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
